circulate/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from . import views

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.home_page, name="home"),
    path('users/', include("users.urls")),
    path('posts/', include("posts.urls")),
    path('profile/', include("userprofile.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

kyverus_game_hub/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name="home"),
    path('users/', include("users.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
   
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("create/", views.post_create, name="create"),
    path("update/<slug:post_slug>", views.post_update, name="update"),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = "profile"

urlpatterns = [
    path("update/", views.update, name="update"),
    path("<slug:public_name>", views.index, name="index"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register_user, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    slug = models.SlugField(default="", null=False)
    private = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='post_banners/fallback.png', blank=True, upload_to="post_banners")
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    date_modified = models.DateTimeField(User, auto_now=True)
    avatar = models.ImageField(default='avatars/default_avatar.png', blank=True, upload_to="avatars")
    banner = models.ImageField(default='profile_banners/default_banner.png', blank=True, upload_to="profile_banners")
    public_name = models.SlugField(max_length=60, blank=True)
    private = models.BooleanField(default=True)
    contact_number = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.user.username
    
# Create User Profile by default when user signs up
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance, public_name=instance.username.lower())
        user_profile.save()

# Automate Profile Creation
post_save.connect(create_profile, sender=User)

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title','body','private','slug','banner']

class UpdatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title','body','private','slug','banner']

userprofile/forms.py
from django import forms
from . import models


class UpdateProfile(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ['avatar', 'banner','public_name', 'private','contact_number']

circulate/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.db.models import Q
from posts.models import Post

def home_page(request):
    if request.user.is_authenticated:
        posts = Post.objects.exclude(~Q(author=request.user), private=True).order_by('date')
    else:
        posts = Post.objects.filter(private=False)
    return render(request, "home_page.html", {"posts":posts})

posts/views.py
from django.shortcuts import render,redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.

@login_required(login_url='/users/login/')
def post_create(request):
    if request.method == "POST":
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid:
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect("profile:index", request.user.profile.public_name)
    else:
        form = forms.CreatePost()
    return render(request, "posts/post_create.html", {"form": form})

@login_required(login_url='/users/login/')
def post_update(request, post_slug):
    obj = Post.objects.get(slug=post_slug)

    form = forms.UpdatePost(instance=obj)
    if request.method == "POST":
        form = forms.UpdatePost(request.POST, request.FILES, instance=obj)
        if form.is_valid:
            form.save()
            return redirect("profile:index", request.user.profile.public_name)
    return render(request, "posts/post_update.html", {"form": form, "post": obj})

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from posts.models import Post
from .models import Profile
from . import forms
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request, public_name):
    profile = Profile.objects.get(public_name=public_name)
    user = User.objects.get(profile=profile)
    userProfile = Profile.objects.get(user=user)

    if userProfile.user == request.user:
        profileDetails = userProfile
        print("match")
    else:
        print("not match")
        if userProfile.private:
            profileDetails = {"avatar": userProfile.avatar, "banner": userProfile.banner, "public_name": userProfile.public_name, "private": userProfile.private}
            print("private")
        else:
            profileDetails = userProfile
            print("not private")
        
    if userProfile.user == request.user:
        posts = Post.objects.filter(author=user)
    else:
        posts = Post.objects.filter(author=user, private=False)
    return render(request, "profile/profile_index.html", {"posts": posts, "profileDetails": profileDetails})

@login_required(login_url='/users/login/')
def update(request):
    obj = Profile.objects.get(user=request.user)
    form = forms.UpdateProfile(instance=obj)
    if request.method == "POST":
        form = forms.UpdateProfile(request.POST,request.FILES, instance=obj)
        if form.is_valid():
            form.save()
            return redirect("profile:index", request.user.profile.public_name)
    return render(request, "profile/profile_update.html", {"form": form})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def register_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("home")
    else: 
        form = UserCreationForm()
    return render(request, "users/user_register.html", {"form": form})

def login_user(request):
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("home")
    else:
        form = AuthenticationForm()
    return render(request, "users/user_login.html", {"form": form})

def logout_user(request):
    if request.method == "POST":
        logout(request)
        return redirect("home")

posts/templates/posts/post_create.html
{% extends "main_layout.html" %}

{% block title  %}
    Create Post
{% endblock  %}

{% block content %}
<h1>Create post</h1>

<div class="container mx-auto max-w-[800px]">
    <form class="custom-form" action="{% url "posts:create" %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            {{form}}
        </div>
        <button class="my-10 px-5 py-2 w-[600px] bg-[cadetblue] outline-none border-none" >
            Create Post
        </button>
    </form>
</div>

{% endblock  %}

posts/templates/posts/post_update.html
{% extends "main_layout.html" %}

{% block title %}
    Update Post
{% endblock  %}

{% block content %}
<div class="container mx-auto max-w-[800px] mt-10">
    <h1 class="text-center font-bold">Update Post</h1>
    <form class="custom-form" action="{% url "posts:update" post_slug=post.slug %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            {{form}}
        </div>
        <button class="my-10 px-5 py-2 w-[600px] bg-[cadetblue] outline-none border-none" >
            Save Changes
        </button>
    </form>
</div> 
{% endblock  %}

templates/home_page.html
{% extends "main_layout.html" %}

{% block title %} 
    Home
{% endblock %}

{% block content %}

<div class="container md:w-[700px] mx-auto flex flex-col mt-10 gap-4">

    {% for post in posts  %}
    <div>
        <div class="flex justify-between space-x-2 bg-blue-950/70 p-2">
            <a href="{% url 'profile:index' public_name=post.author.profile.public_name %}">
            <div class="flex items-center space-x-2">  
               
                    <div class="size-11">
                        <img src="{{post.author.profile.avatar.url}}" alt="{{post.author.profile.public_name}}">
                    </div>
                <div>
                    <h2>@{{post.author}}</h2>
                    <h2>{{post.date}}</h2>
                </div>
            </div>
            </a>
            <div class="flex items-center space-x-2">
                {% if post.private %}
                <div title="Private">
                    {% heroicon_outline "lock-closed" size=20 class="text-white" %}
                </div>
                {% else %}
                <div title="Public">
                    {% heroicon_outline "globe-alt" size=20 class="text-white" %}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="max-w-[800px]">
            <img src="{{post.banner.url}}" alt="{{post.title}}">
        </div>
        <div class="py-2 px-5 bg-blue-950/70">
            <h1 class="font-bold py-2">{{post.title}}</h1>
            <p>{{post.body}}</p>
        </div>
    </div>

    {% endfor %}

</div>
{% endblock %}

templates/main_layout.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title  %} Kyverus Game Hub{% endblock  %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'css/custom.css'%}">
</head>
<body class="bg-gradient-to-b from-[#000000] to-[#03040a] text-white">
    <div class="bg-pattern min-h-dvh pb-10">
        {%  with namespace=request.resolver_match.namespace url_name=request.resolver_match.url_name %}
        <nav class="bg-blue-950 flex justify-between px-5 py-2 items-center">
            <div>
                <a 
                    class = "{% if url_name == 'home' %}text-blue-400{% endif %} font-bold"  
                    href="{% url "home" %}"
                >HOME</a>
            </div>
            <div class="flex space-x-4 items-center">
                {% if user.is_authenticated %}
                
                    <a 
                    class="{% if namespace == 'profile' and url_name == 'index' %}text-blue-400{% endif %} font-bold flex items-center gap-1"
                    href="{% url 'profile:index' public_name=user.profile.public_name %}"
                    >
                    <div class="size-7">
                        <img class="{% if namespace == 'profile' and url_name == 'index' %}border-2 border-blue-500{% endif %} rounded-full" src="{{user.profile.avatar.url}}" alt="{{user.profile.public_name}}">
                    </div>  
                    <div>
                        {{user.username}}
                    </div>
                    </a>
                <form class="logout-form" action="{% url "users:logout" %}" method="post" >
                    {% csrf_token %}
                    <button>LOGOUT</button>
                </form>
                {% else %}
                <a 
                    class="{% if namespace == 'users' and url_name == 'register' %}text-blue-400{% endif %} font-bold" 
                    href="{% url "users:register" %}"
                >REGISTER</a>
                <a  
                    class="{% if namespace == 'users' and url_name == 'login' %}text-blue-400{% endif %} font-bold" 
                    href="{% url "users:login" %}"
                >LOGIN</a>
                {% endif %}
            </div>
        </nav>
        {% endwith %}
    
        {% block content %}
        {% endblock  %}
    </div>
</body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

userprofile/templates/profile/profile_index.html
{% extends "profile/profile_layout.html" %}

{% block posts %}
<div class="container md:w-[700px] mx-auto flex flex-col mt-5 gap-4">
    {% for post in posts  %}
    <div>
        <div class="flex justify-between space-x-2 bg-blue-950/70 p-2">
            <div class="flex items-center space-x-2">
                <div class="size-11">
                    <img src="{{profileDetails.avatar.url}}" alt="{{profileDetails.public_name}}">
                </div>   
                <div>
                    <h2>@{{post.author}}</h2>
                    <h2>{{post.date}}</h2>
                </div>
            </div>

            <div class="flex items-center space-x-2">
                {% if user.is_authenticated %}
                <div class="flex flex-col items-center justify-center">
                    <a type="button" href="{% url "posts:update" post_slug=post.slug %}" class="px-5 bg-blue-600">EDIT POST</a>
                </div>
                {% endif %}
                {% if post.private %}
                <div title="Private">
                    {% heroicon_outline "lock-closed" size=20 class="text-white" %}
                </div>
                {% else %}
                <div title="Public">
                    {% heroicon_outline "globe-alt" size=20 class="text-white" %}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="max-w-[800px]">
            <img src="{{post.banner.url}}" alt="{{post.title}}">
        </div>
        <div class="py-2 px-5 bg-blue-950/70">
            <h1 class="font-bold py-2">{{post.title}}</h1>
            <p>{{post.body}}</p>
        </div>
    </div>
    {% endfor %}
</div>  
{% endblock %}

userprofile/templates/profile/profile_layout.html
{% extends "main_layout.html" %}

{% block title %} 
    Profile
{% endblock %}

{% block content %}

<div class="bg-gray-900">
    <div class="container mx-auto py-10">
        <div class="w-full h-full rounded-t-xl overflow-hidden">
            <img class="object-cover h-[300px] w-full" src="{{profileDetails.banner.url}}" alt="">
        </div>
        <div class="flex gap-4 bg-blue-950/70">
            <div class="p-2 size-[200px]">
                <img class="border-2 border-blue-500 rounded-full" src="{{profileDetails.avatar.url}}" alt="{{profileDetails.public_name}}">
            </div>
            
            <div class="self-center">
                <h1>PUBLIC NAME: {{profileDetails.public_name}}</h1>
    
                {% if profileDetails.contact_number %}
                    <h1>CONTACT NUMBER: {{profileDetails.contact_number}}</h1>
                {% endif %}
            </div>  
        </div>
        {% if user.is_authenticated and user.profile.public_name == profileDetails.public_name %}
        <div class="flex items-center justify-between mt-5 px-5">
            {%  with namespace=request.resolver_match.namespace url_name=request.resolver_match.url_name %}
            <div>
                <a href="#" class="px-5 py-1 {% if namespace == 'profile' and url_name == 'index' %}bg-blue-600{%else%}bg-slate-600{% endif %}" >POSTS</a>
                <a href="#" class="px-5 py-1 {% if namespace == 'profile' and url_name == 'register' %}bg-blue-600{%else%}bg-slate-600{% endif %}" >DASHBOARD</a>
                <a href="#" class="px-5 py-1 {% if namespace == 'profile' and url_name == 'register' %}bg-blue-600{%else%}bg-slate-600{% endif %}" >FOLLOWING</a>
                <a href="#" class="px-5 py-1 {% if namespace == 'profile' and url_name == 'register' %}bg-blue-600{%else%}bg-slate-600{% endif %}" >FOLLOWERS</a>
            </div>
            {% endwith %}
            <div class="space-x-2">
                <a href="{% url "profile:update" %}" class="px-5 py-1 bg-blue-600">EDIT PROFILE</a>
                <a href="{% url "posts:create" %}" class="px-5 py-1 bg-blue-600">CREATE POST</a>
            </div>
        </div>
        {% endif %}
    </div>
</div>


    {% block posts  %} {% endblock  %}

{% endblock %}

userprofile/templates/profile/profile_update.html
{% extends "main_layout.html" %}

{% block title %}
    Update Profile
{% endblock  %}

{% block content %}<h1>Update Profile</h1>
<div class="container mx-auto max-w-[800px]">
    <form class="custom-form" action="{% url "profile:update" %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            {{form}}
        </div>
        <button class="my-10 px-5 py-2 w-[600px] bg-[cadetblue] outline-none border-none" >
            Save Changes
        </button>
    </form>
</div> 
{% endblock  %}

users/templates/users/user_login.html
{% extends "main_layout.html" %}

{% block title  %}
    Login User
{% endblock  %}

{% block content %}
    <div class="container mx-auto max-w-[800px] mt-10">
        <h1 class="text-center font-bold">Login User</h1>
        <form class="custom-form" action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <div>
                {{form}}
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
            </div>
            <button class="my-10 px-5 py-2 w-[600px] bg-[cadetblue] outline-none border-none">
                LOGIN
            </button>
        </form>
    </div>
{% endblock %}

users/templates/users/user_register.html
{% extends "main_layout.html" %}

{% block title  %}
    Register User
{% endblock  %} 

{% block content %}
    <div class="container mx-auto max-w-[800px] mt-10">
        <h1 class="text-center font-bold">Register User</h1>
        <form class="custom-form" action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            <div>
                {{form}}  
            </div>
            <button class="my-10 px-5 py-2 w-[600px] bg-[cadetblue] outline-none border-none">
                REGISTER
            </button>
        </form>
    </div>
{% endblock %}